name: your_gym_bro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  flutter_riverpod: ^3.2.1
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.4
  logging: ^1.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/bgs/
    - assets/images/onboarding/
    - assets/i18n/

  fonts:
    - family: RushDriver
      fonts:
        - asset: assets/fonts/rush_driver/RushDriver-Italic.otf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_24pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_24pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_24pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_24pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_24pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_24pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_24pt-BlackItalic.ttf
          weight: 900
          style: italic
  